// Vue instance
var app = new Vue({
  el: '#app',
  data: {
    works: [
        {"title": "Die Nachtwache", "artist": "Rembrandt van Rijn", "created": "1642", "text": "Das Bild zeigt 34 Personen – davon 18 Schützen und 16 weitere Figuren. Im Vordergrund stehen der Hauptmann und sein Leutnant. Zwei hell erleuchtete Figuren in gelber Kleidung beherrschen den Bildaufbau: ein Mädchen im Mittelgrund und der Leutnant im Vordergrund.", "image_url": "works/rembrandt_nachtwache.jpg"},
        {"title": "Dienstmagd mit Milchkrug", "artist": "Jan Vermeer", "created": "1658-1660", "text": "Im Zentrum des Bildes steht die Frau im Lichteinfall durch ein Fenster auf der linken Seite. Vor ihr befindet sich im linken Bildvordergrund, unter ebendiesem Fenster, ein Tisch, bedeckt mit einem Tuch und bestückt mit einem Brotkorb, einer Kanne und weiteren Speisen. Zudem steht auf dem Tisch eine Schale, in die die Magd Milch eingießt. Ihr Blick ist gesenkt, auf die Tätigkeit konzentriert. Ihre Kleidung wurde in leuchtenden, bunten Farben gemalt. Das gelbe Oberteil steht dabei im Kontrast zum Blau der Schürze, unter der ein langer roter Rock hervorschaut. Der Raum im Hintergrund ist spartanisch eingerichtet, die Rückwand leer und mit erkennbaren Löchern versehen, was ihr den Anschein einer Benutzung über lange Zeit verleiht.", "image_url": "works/vermeer_dienstmagd.jpg"},
        {"title": "Selbstbildnis mit grauem Filzhut", "artist": "Vincent van Gogh", "created": "1887", "text": "Selbstbildnis Van Goghs mit hellem Filzhut, in braunem Überrock", "image_url": "works/gogh_selbstbildnis_filzhut.jpg"},
        {"title": "Caféterasse am Abend", "artist": "Vincent van Gogh", "created": "1888", "text": "Gezeichnet durch van Goghs Eindrücke von Südfrankreich, entsteht eine vollkommen neue Bildentstehung. Er benutzt beispielsweise eine für ihn ungewöhnliche Perspektive. Es ist das erste von vielen mit einem Sternenhimmelhintergrund. So taucht das Motiv des Sternenhimmels beispielsweise in der ebenfalls im September 1888 gemalten Sternennacht über der Rhone (frz. Nuit étoilée sur le Rhône) und in der im Juni 1889 entstandenen Sternennacht (frz. Nuit étoilée) auf.", "image_url": "works/gogh_cafeterasse.jpg"},
        {"title": "Wanderer über dem Nebelmeer", "artist": "Caspar David Friedrich", "created": "1818", "text": "Wanderer über dem Nebelmeer ist ein um 1818 entstandenes Gemälde von Caspar David Friedrich. Das unsignierte Bild in Öl auf Leinwand im Format 74,8 x 94,8 cm befindet sich in der Hamburger Kunsthalle. Der Wanderer ist die bekannteste Rückenfigur des Malers. In der modernen medialen Rezeption wurde das Bild zu einem vielfach verwendeten Symbol der Romantik und zu einer Trivial-Ikone des deutschen Bewusstseins.", "image_url": "works/friedrich_wanderer.jpg"},
        {"title": "Der arme Poet", "artist": "Carl Spitzweg", "created": "1839", "text": "Das Bild zeigt einen Schriftsteller in seiner ärmlichen Dachstube. Das enge Zimmer wird links von einem kleinen Fenster beleuchtet. Rechts sind die Sparren des Hausdachs, an dem ein Regenschirm hängt, der die Schlafstelle vor der durch das Dach tropfenden Feuchtigkeit schützt. Am rechten Bildrand ist die Zimmertür zu erkennen. Gegenüber der Tür, am linken Bildrand, befindet sich ein grüner Kachelofen ohne Feuer darin. Der dargestellte Schriftsteller besitzt kein Bett. Stattdessen liegt an der Wand eine Matratze auf dem Boden, auf der der arme Poet in einem Schlafrock, mit einer Schlafmütze auf dem Kopf liegt. Auf seinen Knien hält er mit der linken Hand einige Manuskriptseiten. Mit der rechten Hand hält er etwas zwischen Daumen und Mittelfinger fest, das er durch seine Brille hindurch fixiert. Vor der Matratze stehen und liegen dicke Bücher sowie zwei Schachteln, auf denen ein Tintenfass steht. Auf dem Rücken des aufrecht stehenden Wälzers stehen die lateinischen Worte: „Gradus ad Parnassum“ (deutsch: „Stufen zum Parnass“), was entweder der Titel des im Jahr 1725 herausgegebenen theoretischen Hauptwerks des österreichischen Komponisten Johann Joseph Fux oder – im Kontext dieses Bildes näherliegend – der von dem Jesuiten Paul Aler in Köln 1702 veröffentlichten Anleitung zum Verfassen lateinischer Verse ist. An die Wand malte der Dichter mit roter Farbe wahrscheinlich das Versmaß des Hexameters. Auf dem grünen Kachelofen steht eine Kerze in der Flasche, daneben die Waschschüssel, an einer Wäscheleine darüber hängt ein Handtuch. Am nicht beheizten Ofenrohr hängt ein Zylinderhut. Im Ofenloch stecken Papierblätter, die wohl zu den Papieren gehören, die vor dem Ofen liegen und die, ebenfalls lateinisch, mit „Operum meorum fasciculum III“ (deutsch: „Das dritte Bündel meiner Werke“) beschriftet sind. Vor dem Ofen liegen außerdem noch ein einzelner Stiefel und ein Stiefelknecht. Links vom Ofen steht ein Mustopf, an der Wand daneben hängt der Ausgehrock und ganz links am Bildrand lehnt der Spazierstock an der Wand. Hinter dem Fenster sind verschneite Dächer. Ein Hinweis darauf, dass es kalt ist. Der Dichter jedoch ist so arm, dass er im Bett liegen bleibt, um sich wenigstens ein bisschen warm zu halten. Heizen kann er nur, wenn er seine Werke verschürt.", "image_url": "works/spitzweg_poet.jpg"},
        {"title": "Das Schokoladenmädchen", "artist": "Jean-Étienne Liotard", "created": "~ 1743 - 1745", "text": "Das Wiener Schokoladenmädchen (“La Belle Chocolatière de Vienne”), eine Pastellmalerei auf Pergament (82,5 × 52,5 cm) von Jean-Étienne Liotard, entstand zwischen 1743 und 1745, vielleicht Dezember 1744. Der Künstler hielt sich in dieser Zeit auf Wunsch der Kaiserin Maria Theresia in Wien auf. Hier malte er sein berühmtestes Pastellbild, das Porträt eines Stubenmädchens.", "image_url": "works/liotard_schokoladenmaedchen.jpg"},
        {"title": "Der Garten der Lüste", "artist": "Hieronymus Bosch", "created": "~ 1500", "text": "Das Dreitafelbild Der Garten der Lüste ist ein Triptychon des niederländischen Malers Hieronymus Bosch (um 1450–1516). Es ist heute im Museo del Prado, Madrid, zu besichtigen. Es gibt keine konkreten Hinweise auf seine Entstehungszeit; die Forschung geht davon aus, dass „Der Garten der Lüste“ um 1500 gemalt wurde. Die beiden Außenflügel zeigen die Schöpfung der Welt am dritten Tag, als Gott nach christlichem Verständnis Land, Meer und Pflanzen schuf. Der linke Innenflügel zeigt den Garten Eden mit Gott, Adam und Eva; die Mitteltafel den Garten der Lüste und der rechte Innenflügel die Hölle. Ausgeklappt misst das Triptychon 220 × 390 cm.", "image_url": "works/bosch_garten.jpg"}
    ],
    selectedWork: null,
    filterText: '',
  },
  computed: {
      filteredWorks: function () {
        self = this;
        return self.works.filter(function (work) {
            return work.title.toLowerCase().indexOf(self.filterText.toLowerCase()) !== -1
        })
      }
  },
  methods: {
      closeDetails: function () {
        this.selectedWork = null
      }
  }
})